version: '3'

services:
  postgres:
    image: postgres:15-alpine
    container_name: logistics-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=logistics
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-users-table.sql:/docker-entrypoint-initdb.d/init-users-table.sql
    restart: unless-stopped
  
  app:
    build: .
    container_name: logistics-app
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - DB_NAME=logistics
      - JWT_SECRET=your-secret-key-change-in-production
      - NODE_ENV=production
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data: